# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NtpClientSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntp_client_name', models.CharField(max_length=30)),
                ('ntp_server_ip', models.CharField(max_length=30)),
                ('update_interval', models.IntegerField()),
            ],
        ),
    ]
